name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Run ctest
      run: docker run my-image-name
    - name: ctest
      run: docker run -w /app/build-docker -t my-image-name ctest
    - name: clang-tidy
      run: docker run -w /app/build-docker -t my-image-name run-clang-tidy-14.py
